### ISSUE TITLE
alternative parser doesn't seem to work

### ISSUE THREAD

**Issue by radu-gheorghe** [rsyslog/liblognorm#153]
I'm trying out liblognorm v2 trying to make a parser for apache logs. All looks good so far but I'm trying the new alternative parser and it doesn't seem to be recognized. lognormalizer complains:

```
liblognorm: parser 16: { "type": "alternative", "parser": [ { "type": "number", "name": "bytes" }, { "type": "literal", "text": "-" } ] }
liblognorm error: rulebase file /opt/rsyslog/apache.rb[27]: invalid field type 'alternative'
```

Which is weird, my config looks very similar to one of those used in tests. That said, I didn't run the tests to see if they fail or not - maybe it's a known issue?

Here's my current config for reference:

```
version=2

rule=:%[
  {"type": "word", "name": "clientip"},
  {"type": "literal", "text": " "},
  {"type": "word", "name": "ident"},
  {"type": "literal", "text": " "},
  {"type": "word", "name": "auth"},
  {"type": "literal", "text": " ["},
  {"type": "char-to", "name": "timestamp", "extradata": "]"},
  {"type": "literal", "text": "] \""},
  {"type": "word", "name": "verb"},
  {"type": "literal", "text": " "},
  {"type": "word", "name": "request"},
  {"type": "literal", "text": " HTTP/"},
  {"type": "float", "name": "httpversion"},
  {"type": "literal", "text": "\" "},
  {"type": "number", "name": "response"},
  {"type": "literal", "text": " "},
  {"type":"alternative",
   "parser": [
     {"type": "number", "name": "bytes"},
     {"type": "literal", "text": "-"}
   ]
  },
  {"type": "literal", "text": " "},
  {"type": "rest", "name": "blob"}
]%
```

If I remove the "alternative" one it works fine.

**Comment by rgerhards** [comment]
could you give it a re-test with current master branch. There have been a couple of changes and I think this could have been fixed.

**Comment by ontholerian** [comment]
I have built the project from commit 3b339fa, and can confirm there is still an issue with the alternative parser. See the example log input (test.log) and rulesfile (test.conf). There should not be any spaces at the ends of any of these lines.

------------------------------------------------
$ cat test.log
1.2.3.4 sam 25
1.2.3.5 john 36
1.2.3.6 - 75
127.0.0.1 - -
$ cat test.conf
version=2

# Simple case, no issue
#rule=:%ip:ipv4% %username:word% %bytes:number%

# Alternative with literal/number, no issue (number is presented as string?)
#rule=:%ip:ipv4% %username:word% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"number","name":"bytes"}]}%

# Alternative with literal/word, core dumps
rule=:%ip:ipv4% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"word","name":"username"}]}% %bytes:number%

# Alternatives with literal/word and literal/number, code dumps
#rule=:%ip:ipv4% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"word","name":"username"}]}% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"number","name":"bytes"}]}%
------------------------------------------------

The comments above the rules indicate which ones triggers a core dump and which ones do not. Taking a look at the dump, it appears there that prs->node is NULL when it should not be, or a check for it being NULL is missing. I did a  simple test on pdag.c:352 (added " && prs->node != NULL"), and the program core dumped later down the ln_pdagComponentOptimize() chain call, demonstrating that the prs->node NULL check avoided the initial core dump trigger.

**Comment by ontholerian** [comment]
oops, apologies for the lack of Markdown escaping.

------
<pre>
$ cat test.log
1.2.3.4 sam 25
1.2.3.5 john 36
1.2.3.6 - 75
127.0.0.1 - -
</pre>
------
<pre>
$ cat test.conf
version=2


# Simple case, no issue
#rule=:%ip:ipv4% %username:word% %bytes:number%

# Alternative with literal/number, no issue (number is presented as string?)
#rule=:%ip:ipv4% %username:word% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"number","name":"bytes"}]}%

# Alternative with literal/word, core dumps
rule=:%ip:ipv4% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"word","name":"username"}]}% %bytes:number%

# Alternatives with literal/word and literal/number, code dumps
#rule=:%ip:ipv4% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"word","name":"username"}]}% %{"type":"alternative","parser":[{"type":"literal","text":"-"},{"type":"number","name":"bytes"}]}%
</pre>
-------

**Comment by TD-4242** [comment]
when I try that it doesn't seem to work at all, says alternative is invalid.

```
$>cat test.log |/usr/lib/lognorm/lognormalizer -r test.conf -e json
liblognorm error: rulebase file test.conf[12]: invalid field type '"alternative","parser"'
{ "originalmsg": "1.2.3.4 sam 25", "unparsed-data": "sam 25" }
{ "originalmsg": "1.2.3.5 john 36", "unparsed-data": "john 36" }
{ "originalmsg": "1.2.3.6 - 75", "unparsed-data": "- 75" }
{ "originalmsg": "127.0.0.1 - -", "unparsed-data": "- -" }
```

this is using a recent version from the deb repo:
```
$>/usr/lib/lognorm/lognormalizer -V
lognormalizer version: 2.0.0.764167d00c98
liblognorm version: 2.0.0.764167d00c98
        advanced stats: not available
```

**Comment by rgerhards** [comment]
How does your rulebase look like? Do you opt-in to the v2 engine by using ```version=2``` in the first line?

**Comment by TD-4242** [comment]
yes, had the v2 engine.  This was using the rulebase in the previous comment.

**Comment by davidelang** [comment]
On Wed, 20 Apr 2016, Bill Warner wrote:

> yes, had the v2 engine.  This was using the rulebase in the previous comment.

I also tried alternative again a couple weeks ago and didn't get it to work

I was trying:

type=@endpid:%{"type":"alternative","parser":[ {"type": "literal", 
"text":"]"},{"type": "literal", "text":"]:"} ] }%

because sometimes things are getting to me as program[pid] and sometimes as 
program[pid]: (depending on if they were sent as rfc5424 for a hop or not, if 
they were received by rsyslog as rfc5424 then syslogtag won't have the : at the 
end)

David Lang

**Comment by mostolog** [comment]
Probably related
https://github.com/rsyslog/liblognorm/issues/236
https://github.com/rsyslog/liblognorm/issues/235

**Comment by radu-gheorghe** [comment]
I've used `alternative` and it worked OK for me. The problem was (and I've seen this with others, too) that there were multiple instances of lognormalizer on the machine. Initially, I had the same problem with rsyslog, but that's because it wasn't using liblognorm v2 yet.

@mostolog can you check wheter lognormalizer is linked to the newest liblognorm? It should look something like this (at least on Ubuntu):

```
# ldd /usr/lib/lognorm/lognormalizer | grep liblognorm
# other libraries
liblognorm.so.5 => /usr/lib/liblognorm.so.5
```

Maybe this explains #236, though I'm not sure about #235

**Comment by mostolog** [comment]
Happy new year!

```
root@myrsyslog:/# /usr/lib/lognorm/lognormalizer -V
lognormalizer version: 2.0.2
liblognorm version: 2.0.2
	advanced stats: not available

root@myrsyslog:/# ldd /usr/lib/lognorm/lognormalizer                  
	linux-vdso.so.1 =>  (0x00007ffcbff03000)
	libfastjson.so.4 => /usr/lib/libfastjson.so.4 (0x00007fd826574000)
	liblognorm.so.5 => /usr/lib/liblognorm.so.5 (0x00007fd826353000)
	libestr.so.0 => /usr/lib/x86_64-linux-gnu/libestr.so.0 (0x00007fd82614f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd825d86000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd826983000)

root@myrsyslog:/# cat a.rb 
version=2

rule=:%[
{"type":"alternative","parser":[
	{"type":"literal", "text":"a"},
	{"type":"literal", "text":"b"}
]},
{"type":"literal", "text":"c"}]%

root@myrsyslog:/# echo "ac" | /usr/lib/lognorm/lognormalizer -r a.rb
liblognorm error: rulebase file a.rb[8]: invalid field type 'alternative'
{ "originalmsg": "ac", "unparsed-data": "ac" }
```

Let me know if you need further testing
Regards
